package br.cefet.sicom.modelo;

public enum TipoDeAcao {
	
	CADASTRO_DE_USUARIO, LIBERACAO_DE_MATERIAL, ATUALIZACAO_DE_MATERIAL, CADASTRO_DE_MATERIAL, REMOCAO_DE_MATERIAL,
	CADASTRO_DE_SOLICITANTE, LANCAMENTO_DE_ENTRADA, IMPRESSAO_DE_RELATORIO, IMPRESSAO_DE_COMPROVANTE, LOGIN_NO_SISTEMA;
	

}
